# Generated by Django 5.1.4 on 2025-01-20 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advantages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='RepaymentMethods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, verbose_name='Назва')),
                ('offer_url', models.URLField(verbose_name='Посилання на оффер')),
                ('image', models.ImageField(upload_to='offers/', verbose_name='Лого офферу')),
                ('first_amount', models.IntegerField(verbose_name='Перший кредит - макс грн.')),
                ('second_amount', models.IntegerField(verbose_name='Повторний кредит макс грн.')),
                ('amount_from', models.IntegerField(verbose_name='Кредит від грн.')),
                ('amount_to', models.IntegerField(verbose_name='Кредит до грн.')),
                ('percent_per_day', models.DecimalField(decimal_places=4, max_digits=15, verbose_name='Відсотків на день')),
                ('term_from', models.IntegerField(verbose_name='Кредит від - днів')),
                ('term_to', models.IntegerField(verbose_name='Кредит до - днів')),
                ('real_annual_rate_from', models.DecimalField(decimal_places=4, max_digits=15, verbose_name='Реальна річна ставка від')),
                ('real_annual_rate_to', models.DecimalField(decimal_places=4, max_digits=15, verbose_name='Реальна річна ставка до')),
                ('days_rate', models.DecimalField(decimal_places=4, max_digits=15, verbose_name='Денна відсодкова ставка')),
                ('age', models.IntegerField(verbose_name='Вік до')),
                ('cash', models.BooleanField(verbose_name='Готівкою')),
                ('card', models.BooleanField(verbose_name='На картку')),
                ('time_to_get', models.IntegerField(verbose_name='Час на отримання коштів')),
                ('on_lending', models.BooleanField(verbose_name='Перекредитування')),
                ('bank_card', models.BooleanField(verbose_name='На банківську картку')),
                ('passport', models.BooleanField(verbose_name='Паспорт')),
                ('bankID', models.BooleanField(verbose_name='Верифікація через bankID')),
                ('code', models.BooleanField(verbose_name='ІПН')),
                ('around_the_clock', models.BooleanField(verbose_name='Цілодобово')),
                ('basic_characteristics_href', models.URLField(verbose_name='Посилання на Істотні характеристики послуги')),
                ('user_warning', models.URLField(verbose_name='Посилання на попередження для користувача')),
                ('license', models.CharField(max_length=200, verbose_name='Ліцензія')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('address', models.CharField(max_length=200, verbose_name='Адреса')),
                ('phone', models.CharField(max_length=200, verbose_name='Телефон')),
                ('legal_entity', models.CharField(max_length=200, verbose_name='Юридична особа')),
                ('advantages', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='offers_api.advantages', verbose_name='Переваги')),
                ('documents', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='offers_api.documents', verbose_name='Документи')),
                ('repayment_methods', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='offers_api.repaymentmethods', verbose_name='Способи погашення')),
            ],
        ),
    ]
