# Generated by Django 5.1.4 on 2025-01-22 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers_api', '0003_alter_offer_options_offer_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='advantages',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='documents',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='repayment_methods',
        ),
        migrations.AddField(
            model_name='offer',
            name='advantages',
            field=models.ManyToManyField(blank=True, null=True, to='offers_api.advantages', verbose_name='Переваги'),
        ),
        migrations.AddField(
            model_name='offer',
            name='documents',
            field=models.ManyToManyField(blank=True, null=True, to='offers_api.documents', verbose_name='Документи'),
        ),
        migrations.AddField(
            model_name='offer',
            name='repayment_methods',
            field=models.ManyToManyField(blank=True, null=True, to='offers_api.repaymentmethods', verbose_name='Способи погашення'),
        ),
    ]
