# Generated by Django 5.1.4 on 2025-01-24 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers_api', '0004_remove_offer_advantages_remove_offer_documents_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='advantages',
            field=models.ManyToManyField(blank=True, to='offers_api.advantages', verbose_name='Переваги'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='documents',
            field=models.ManyToManyField(blank=True, to='offers_api.documents', verbose_name='Документи'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='repayment_methods',
            field=models.ManyToManyField(blank=True, to='offers_api.repaymentmethods', verbose_name='Способи погашення'),
        ),
    ]
