# Generated by Django 5.1.4 on 2025-01-25 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers_api', '0005_alter_offer_advantages_alter_offer_documents_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='recommended',
            field=models.BooleanField(default=False, verbose_name='Рекомендовано'),
        ),
    ]
