# Generated by Django 5.1.4 on 2025-01-26 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers_api', '0006_offer_recommended'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='show_offer',
            field=models.BooleanField(default=True, verbose_name='Активний оффер ?'),
        ),
    ]
