# Generated by Django 5.1.4 on 2025-02-04 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers_api', '0007_offer_show_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='zero_first',
            field=models.BooleanField(default=False, verbose_name='Перший під 0% ?'),
        ),
    ]
