# Generated by Django 5.1.4 on 2025-02-06 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers_api', '0008_offer_zero_first'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='offer_advantage',
            field=models.CharField(default='offer_advantage', max_length=200, verbose_name='Перевага'),
        ),
    ]
