# Generated by Django 5.1.4 on 2025-02-08 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers_api', '0009_offer_offer_advantage'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='country',
            field=models.CharField(choices=[('PL', 'Poland'), ('UA', 'Ukraine')], default='UA', max_length=2, verbose_name='Країна'),
        ),
    ]
