# Generated by Django 5.1.4 on 2025-02-08 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers_api', '0010_offer_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='calculate_template',
            field=models.TextField(blank=True, null=True),
        ),
    ]
