# Generated by Django 5.1.4 on 2025-01-24 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question', models.CharField(max_length=255, verbose_name='Запитання')),
                ('answer', models.TextField(verbose_name='Відповідь')),
                ('show_in_main', models.BooleanField(default=False, verbose_name='На головну')),
            ],
        ),
    ]
