# Generated by Django 5.1.4 on 2025-01-26 14:03

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_settings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='faq_page_text',
            field=ckeditor.fields.RichTextField(default='faq text', verbose_name='Текст FAQ'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='main_page_text',
            field=ckeditor.fields.RichTextField(default='main text', verbose_name='Текст головної сторінки'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='pages_text',
            field=ckeditor.fields.RichTextField(default='pages text', verbose_name='Текст категорії Pages'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='enable_feature',
            field=models.BooleanField(default=True, verbose_name='Робочий стан'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='site_name',
            field=models.CharField(default='Мій сайт', max_length=255),
        ),
    ]
