# Generated by Django 5.1.4 on 2025-01-26 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_settings', '0002_sitesettings_faq_page_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='faq_page_h1',
            field=models.CharField(default='faq h1', max_length=255, verbose_name='H1 для FAQ'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='faq_page_meta_desc',
            field=models.CharField(default='meta desc faq', max_length=255, verbose_name='Мета опис FAQ'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='faq_page_title',
            field=models.CharField(default='title faq', max_length=255, verbose_name='Title FAQ'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='main_page_h1',
            field=models.CharField(default='main h1', max_length=255, verbose_name='H1 головної сторінки'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='main_page_meta_desc',
            field=models.CharField(default='meta desc', max_length=255, verbose_name='Мета опис головної сторінки'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='main_page_title',
            field=models.CharField(default='title h1', max_length=255, verbose_name='Title головної сторінки'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='pages_meta_desc',
            field=models.CharField(default='pages meta desc', max_length=255, verbose_name='Мета опис категорії Pages'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='pages_page_h1',
            field=models.CharField(default='pages h1', max_length=255, verbose_name='H1 для категорії Pages'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='pages_title',
            field=models.CharField(default='pages title', max_length=255, verbose_name='Title категорії Pages'),
        ),
    ]
