# Generated by Django 5.1.4 on 2025-01-29 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_settings', '0003_sitesettings_faq_page_h1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='faq_page_og_image',
            field=models.ImageField(blank=True, null=True, upload_to='pages/', verbose_name='Зображення для Open Graf'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='main_page_og_image',
            field=models.ImageField(blank=True, null=True, upload_to='pages/', verbose_name='Зображення для Open Graf'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='pages_og_image',
            field=models.ImageField(blank=True, null=True, upload_to='pages/', verbose_name='Зображення для Open Graf'),
        ),
    ]
