# Generated by Django 5.1.4 on 2025-01-30 12:23

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_settings', '0004_sitesettings_faq_page_og_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='text_for_google_term',
            field=ckeditor.fields.RichTextField(default='text_for_google_term', verbose_name='Текст для Google з умовами'),
        ),
    ]
