# Generated by Django 5.1.4 on 2025-01-30 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_settings', '0005_sitesettings_text_for_google_term'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='footer_text',
            field=models.CharField(default='footer_text', max_length=255, verbose_name='Текст для футера'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='show_pages',
            field=models.BooleanField(default=False, verbose_name='Показувати статті'),
        ),
    ]
