# Generated by Django 5.1.4 on 2025-01-30 12:49

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_settings', '0006_sitesettings_footer_text_sitesettings_show_pages'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='ranking_page_h1',
            field=models.CharField(default='ranking h1', max_length=255, verbose_name='H1 для Ranking'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='ranking_page_meta_desc',
            field=models.CharField(default='ranking desc faq', max_length=255, verbose_name='Мета опис Ranking'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='ranking_page_og_image',
            field=models.ImageField(blank=True, null=True, upload_to='pages/', verbose_name='Зображення для Open Graf - Ranking'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='ranking_page_text',
            field=ckeditor.fields.RichTextField(default='Ranking text', verbose_name='Текст FAQ'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='ranking_page_title',
            field=models.CharField(default='ranking faq', max_length=255, verbose_name='Title Ranking'),
        ),
    ]
