# Generated by Django 5.1.4 on 2025-01-30 12:56

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_settings', '0007_sitesettings_ranking_page_h1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='logo_img',
            field=models.ImageField(blank=True, null=True, upload_to='pages/', verbose_name='logo'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='ranking_page_text',
            field=ckeditor.fields.RichTextField(default='Ranking text', verbose_name='Текст Ranking'),
        ),
    ]
