# Generated by Django 5.1.4 on 2025-01-31 22:26

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_settings', '0008_sitesettings_logo_img_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='site_policy',
            field=ckeditor.fields.RichTextField(default='Політика конфиденційності', verbose_name='Політика конфиденційності'),
        ),
    ]
