# Generated by Django 5.1.4 on 2025-01-24 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meta_title', models.CharField(max_length=255, verbose_name='Мета заголовок')),
                ('meta_description', models.CharField(max_length=255, verbose_name='Мета опис')),
                ('image', models.ImageField(upload_to='pages/', verbose_name='Зображення')),
                ('h1', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('text', models.TextField()),
                ('show_in_main_menu', models.BooleanField(default=False, verbose_name='Показувати в головному меню ?')),
            ],
        ),
    ]
