# Generated by Django 5.1.4 on 2025-01-24 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages_api', '0003_page_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='url',
            field=models.SlugField(blank=True, max_length=255, unique=True, verbose_name='URL-имя'),
        ),
    ]
