# Generated by Django 5.1.4 on 2025-01-24 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages_api', '0004_page_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='page',
            old_name='url',
            new_name='slug',
        ),
    ]
