# Generated by Django 5.1.4 on 2025-01-28 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages_api', '0006_alter_page_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='image_full',
            field=models.ImageField(blank=True, null=True, upload_to='pages/', verbose_name='Зображення для статті'),
        ),
        migrations.AlterField(
            model_name='page',
            name='image',
            field=models.ImageField(upload_to='pages/', verbose_name='Зображення для категорії'),
        ),
    ]
