# Generated by Django 5.1.4 on 2025-01-29 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages_api', '0007_page_image_full_alter_page_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='og_image',
            field=models.ImageField(blank=True, null=True, upload_to='pages/', verbose_name='Зображення для статті'),
        ),
    ]
