# Generated by Django 5.1.4 on 2025-01-29 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages_api', '0008_page_og_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='og_image',
            field=models.ImageField(blank=True, null=True, upload_to='pages/', verbose_name='Зображення для Open Graf'),
        ),
    ]
